version: '3.8'

services:
  hrfco-mcp:
    build: .
    container_name: hrfco-mcp-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HRFCO_API_KEY=${HRFCO_API_KEY}
      - KMA_API_KEY=${KMA_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hrfco-network

  # Cloudflare Tunnel (선택사항)
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - hrfco-mcp
    networks:
      - hrfco-network
    profiles:
      - cloudflare

networks:
  hrfco-network:
    driver: bridge

volumes:
  logs:
    driver: local 