version: '3.8'

services:
  hrfco-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HRFCO_API_KEY=${HRFCO_API_KEY}
      - LOG_LEVEL=INFO
      - CACHE_TTL_SECONDS=300
      - MAX_CONCURRENT_REQUESTS=5
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 개발용 Redis 캐시 (선택사항)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - cache

volumes:
  redis_data: 