apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrfco-mcp-server
  labels:
    app: hrfco-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrfco-mcp-server
  template:
    metadata:
      labels:
        app: hrfco-mcp-server
    spec:
      containers:
      - name: hrfco-service
        image: hrfco-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: HRFCO_API_KEY
          valueFrom:
            secretKeyRef:
              name: hrfco-secrets
              key: api-key
        - name: LOG_LEVEL
          value: "INFO"
        - name: CACHE_TTL_SECONDS
          value: "300"
        - name: MAX_CONCURRENT_REQUESTS
          value: "5"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hrfco-mcp-service
spec:
  selector:
    app: hrfco-mcp-server
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: hrfco-secrets
type: Opaque
data:
  api-key: <base64-encoded-api-key> 