[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/search-station"
  to = "/.netlify/functions/search-station"
  status = 200

[[redirects]]
  from = "/api/get-water-info"
  to = "/.netlify/functions/get-water-info"
  status = 200

[[redirects]]
  from = "/api/recommend-stations"
  to = "/.netlify/functions/recommend-stations"
  status = 200

[[redirects]]
  from = "/api/openai-functions"
  to = "/.netlify/functions/openai-functions"
  status = 200

[[redirects]]
  from = "/api/mcp"
  to = "/.netlify/functions/mcp"
  status = 200

[build.environment]
  NODE_VERSION = "18"
