name: Deploy HRFCO MCP Server (Docker Hub Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 수동 실행 가능

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        HRFCO_API_KEY: ${{ secrets.HRFCO_API_KEY }}
      run: |
        python test_api.py

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # 안정적인 빌드 설정
        driver-opts: |
          image=moby/buildkit:latest
          network=host
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push optimized image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/hrfco-mcp-server:latest
          ${{ secrets.DOCKER_USERNAME }}/hrfco-mcp-server:${{ github.sha }}
        build-args: |
          HRFCO_API_KEY=${{ secrets.HRFCO_API_KEY }}
        # 캐시 비활성화로 안정성 확보
        cache-from: ""
        cache-to: ""
        platforms: linux/amd64
        provenance: false
        sbom: false
    
    - name: Deploy to Glama
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.GLAMA_HOST }}
        username: ${{ secrets.GLAMA_USERNAME }}
        key: ${{ secrets.GLAMA_SSH_KEY }}
        script: |
          cd /opt/hrfco-service
          echo "Pulling latest image from Docker Hub..."
          docker-compose pull
          echo "Starting services..."
          docker-compose up -d
          echo "Deployment completed successfully!"
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/hrfco-mcp-server:latest" 